# Site settings
name: Elizabeth Ashley Menezes
title: Elizabeth Ashley Menezes | Scientist
description: Design-minded scientist focused on communicating beautiful science & user experiences 
url: https://elizabeth-ashley.github.io/
baseurl: ''
email: designer.elizabeth.ashley@gmail.com
cover: https://bchiang7.github.io/img/og.png
logo: https://bchiang7.github.io/img/emojis/technologist.png
resume: https://bchiang7.github.io/resume.pdf
social:
  - title: email
    url: mailto:designer.elizabeth.ashley@gmail.com
  - title: twitter
    url: https://twitter.com/seismacita
  - title: instagram
    url: https://instagram.com/seismacita
  - title: github
    url: https://github.com/elizabeth-ashley

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
